<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Simple" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="Dock.Avalonia" />
    <PackageReference Include="Dock.Avalonia.Themes.Simple" />
    <PackageReference Include="Dock.Model.Mvvm" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Stampeded.Core\Stampeded.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Editor\*.xshd" />
  </ItemGroup>
</Project>
