<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RollForward>Major</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Simple" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="TextMateSharp" />
    <PackageReference Include="TextMateSharp.Grammars" />
    <PackageReference Include="Dock.Avalonia" />
    <PackageReference Include="Markdown.Avalonia" />
    <PackageReference Include="Dock.Avalonia.Themes.Simple" />
    <PackageReference Include="Dock.Model.Mvvm" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Stampeded.Core\Stampeded.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/**/*.svg" />
    <EmbeddedResource Include="Editor/ILAsm-Mode.xshd" />
  </ItemGroup>
</Project>
